/** AUTO-GENERATED by scripts/regenerate-extractor-registry.mjs — do not edit */
import type { ExtractedVideo, ExtractorDef } from "../types.js";
import { fetchText } from "../http.js";
import { BROWSER_UA } from "../http.js";
import { vixcloudExtractor } from "./vixcloud.js";
import { rabbitstreamExtractor } from "./rabbitstream.js";
import { vidplayExtractor } from "./vidplay.js";
import { streamtapeExtractor } from "./streamtape.js";
import { voeExtractor } from "./voe.js";
import { filemoonExtractor } from "./filemoon.js";
import { mixdropExtractor } from "./mixdrop.js";
import { loadxExtractor } from "./loadx.js";
import { doodLaExtractor } from "./dood-la.js";
import { streamWishExtractor } from "./stream-wish.js";
import { vidGuardExtractor } from "./vid-guard.js";
import { twoEmbedExtractor } from "./two-embed.js";
import { afterDarkExtractor } from "./after-dark.js";
import { amazonDriveExtractor } from "./amazon-drive.js";
import { apiVoirFilmExtractor } from "./api-voir-film.js";
import { bigWarpExtractor } from "./big-warp.js";
import { chillxJeanExtractor } from "./chillx-jean.js";
import { chillxExtractor } from "./chillx.js";
import { closeloadExtractor } from "./closeload.js";
import { dailymotionExtractor } from "./dailymotion.js";
import { doodLaDoodLiExtractor } from "./dood-la-dood-li.js";
import { doodLaDoodExtractor } from "./dood-la-dood.js";
import { droploadExtractor } from "./dropload.js";
import { einschaltenExtractor } from "./einschalten.js";
import { frembedExtractor } from "./frembed.js";
import { fsvidExtractor } from "./fsvid.js";
import { goodstreamExtractor } from "./goodstream.js";
import { googleDriveExtractor } from "./google-drive.js";
import { guploadExtractor } from "./gupload.js";
import { gxPlayerExtractor } from "./gx-player.js";
import { hxfileExtractor } from "./hxfile.js";
import { lamovieExtractor } from "./lamovie.js";
import { loadXExtractor } from "./load-x.js";
import { luluVdoExtractor } from "./lulu-vdo.js";
import { mStreamDayExtractor } from "./m-stream-day.js";
import { magaSavorExtractor } from "./maga-savor.js";
import { mailRuExtractor } from "./mail-ru.js";
import { maxstreamExtractor } from "./maxstream.js";
import { mixDropExtractor } from "./mix-drop.js";
import { moflixExtractor } from "./moflix.js";
import { moviesapiExtractor } from "./moviesapi.js";
import { mp4uploadExtractor } from "./mp4upload.js";
import { myFileStorageExtractor } from "./my-file-storage.js";
import { nekostreamExtractor } from "./nekostream.js";
import { ninjaStreamExtractor } from "./ninja-stream.js";
import { nuuploadExtractor } from "./nuupload.js";
import { okruExtractor } from "./okru.js";
import { onRegardeOuExtractor } from "./on-regarde-ou.js";
import { oneuploadExtractor } from "./oneupload.js";
import { pDrainExtractor } from "./p-drain.js";
import { pcloudExtractor } from "./pcloud.js";
import { plusPomlaExtractor } from "./plus-pomla.js";
import { primeSrcExtractor } from "./prime-src.js";
import { rabbitstreamDokicloudExtractor } from "./rabbitstream-dokicloud.js";
import { rabbitstreamMegacloudExtractor } from "./rabbitstream-megacloud.js";
import { rabbitstreamPremiumEmbedingExtractor } from "./rabbitstream-premium-embeding.js";
import { ridooExtractor } from "./ridoo.js";
import { rpmvidExtractor } from "./rpmvid.js";
import { saveFilesExtractor } from "./save-files.js";
import { shareCloudyExtractor } from "./share-cloudy.js";
import { streamSbExtractor } from "./stream-sb.js";
import { streamUpExtractor } from "./stream-up.js";
import { streamWishHlswishExtractor } from "./stream-wish-hlswish.js";
import { streamWishPlayerwishExtractor } from "./stream-wish-playerwish.js";
import { streamWishSwiftPlayersExtractor } from "./stream-wish-swift-players.js";
import { streamWishSwishExtractor } from "./stream-wish-swish.js";
import { streamWishUqloadsXyzExtractor } from "./stream-wish-uqloads-xyz.js";
import { streamhubExtractor } from "./streamhub.js";
import { streamixExtractor } from "./streamix.js";
import { streamlareExtractor } from "./streamlare.js";
import { streamrubyExtractor } from "./streamruby.js";
import { supervideoExtractor } from "./supervideo.js";
import { uchExtractor } from "./uch.js";
import { upZurExtractor } from "./up-zur.js";
import { upzoneExtractor } from "./upzone.js";
import { uqloadExtractor } from "./uqload.js";
import { ustrExtractor } from "./ustr.js";
import { veevExtractor } from "./veev.js";
import { vidHideExtractor } from "./vid-hide.js";
import { vidLinkExtractor } from "./vid-link.js";
import { vidMoLyToDomainExtractor } from "./vid-mo-ly-to-domain.js";
import { vidMoLyExtractor } from "./vid-mo-ly.js";
import { vidPlyExtractor } from "./vid-ply.js";
import { vidaraExtractor } from "./vidara.js";
import { videasyExtractor } from "./videasy.js";
import { videoSibNetExtractor } from "./video-sib-net.js";
import { vidflixExtractor } from "./vidflix.js";
import { vidnestExtractor } from "./vidnest.js";
import { vidoraExtractor } from "./vidora.js";
import { vidozaExtractor } from "./vidoza.js";
import { vidplayMyCloudExtractor } from "./vidplay-my-cloud.js";
import { vidplayVidplayOnlineExtractor } from "./vidplay-vidplay-online.js";
import { vidrockExtractor } from "./vidrock.js";
import { vidsonicExtractor } from "./vidsonic.js";
import { vidsrcNetExtractor } from "./vidsrc-net.js";
import { vidsrcRuExtractor } from "./vidsrc-ru.js";
import { vidsrcToExtractor } from "./vidsrc-to.js";
import { vidxGoExtractor } from "./vidx-go.js";
import { vidzeeExtractor } from "./vidzee.js";
import { vidzyExtractor } from "./vidzy.js";
import { vixSrcExtractor } from "./vix-src.js";
import { vtubeExtractor } from "./vtube.js";
import { yourUploadExtractor } from "./your-upload.js";
import { zillaExtractor } from "./zilla.js";

const EXTRACTORS: ExtractorDef[] = [
  vixcloudExtractor,
  rabbitstreamExtractor,
  vidplayExtractor,
  streamtapeExtractor,
  voeExtractor,
  filemoonExtractor,
  mixdropExtractor,
  loadxExtractor,
  doodLaExtractor,
  streamWishExtractor,
  vidGuardExtractor,
  twoEmbedExtractor,
  afterDarkExtractor,
  amazonDriveExtractor,
  apiVoirFilmExtractor,
  bigWarpExtractor,
  chillxJeanExtractor,
  chillxExtractor,
  closeloadExtractor,
  dailymotionExtractor,
  doodLaDoodLiExtractor,
  doodLaDoodExtractor,
  droploadExtractor,
  einschaltenExtractor,
  frembedExtractor,
  fsvidExtractor,
  goodstreamExtractor,
  googleDriveExtractor,
  guploadExtractor,
  gxPlayerExtractor,
  hxfileExtractor,
  lamovieExtractor,
  loadXExtractor,
  luluVdoExtractor,
  mStreamDayExtractor,
  magaSavorExtractor,
  mailRuExtractor,
  maxstreamExtractor,
  mixDropExtractor,
  moflixExtractor,
  moviesapiExtractor,
  mp4uploadExtractor,
  myFileStorageExtractor,
  nekostreamExtractor,
  ninjaStreamExtractor,
  nuuploadExtractor,
  okruExtractor,
  onRegardeOuExtractor,
  oneuploadExtractor,
  pDrainExtractor,
  pcloudExtractor,
  plusPomlaExtractor,
  primeSrcExtractor,
  rabbitstreamDokicloudExtractor,
  rabbitstreamMegacloudExtractor,
  rabbitstreamPremiumEmbedingExtractor,
  ridooExtractor,
  rpmvidExtractor,
  saveFilesExtractor,
  shareCloudyExtractor,
  streamSbExtractor,
  streamUpExtractor,
  streamWishHlswishExtractor,
  streamWishPlayerwishExtractor,
  streamWishSwiftPlayersExtractor,
  streamWishSwishExtractor,
  streamWishUqloadsXyzExtractor,
  streamhubExtractor,
  streamixExtractor,
  streamlareExtractor,
  streamrubyExtractor,
  supervideoExtractor,
  uchExtractor,
  upZurExtractor,
  upzoneExtractor,
  uqloadExtractor,
  ustrExtractor,
  veevExtractor,
  vidHideExtractor,
  vidLinkExtractor,
  vidMoLyToDomainExtractor,
  vidMoLyExtractor,
  vidPlyExtractor,
  vidaraExtractor,
  videasyExtractor,
  videoSibNetExtractor,
  vidflixExtractor,
  vidnestExtractor,
  vidoraExtractor,
  vidozaExtractor,
  vidplayMyCloudExtractor,
  vidplayVidplayOnlineExtractor,
  vidrockExtractor,
  vidsonicExtractor,
  vidsrcNetExtractor,
  vidsrcRuExtractor,
  vidsrcToExtractor,
  vidxGoExtractor,
  vidzeeExtractor,
  vidzyExtractor,
  vixSrcExtractor,
  vtubeExtractor,
  yourUploadExtractor,
  zillaExtractor,
];

const URL_PREFIX_RE = /^(https?:\/\/)?(www\.)?/i;

function normalizeCompareUrl(link: string): string {
  return link.toLowerCase().replace(URL_PREFIX_RE, "");
}

function stripDomain(url: string): string {
  return url.replace(/^(https?:\/\/)?(www\.)?(.*?)(\.[a-z]+)/i, "$3");
}

async function resolveBridge(link: string): Promise<string> {
  if (!link.includes("mysync.mov/stream/")) return link;
  try {
    const html = await fetchText(link, { headers: { "User-Agent": BROWSER_UA } });
    for (const re of [/window\.location\.replace\("([^"]+)"/, /src="(https?:\/\/[^"]+)"/]) {
      const m = html.match(re);
      if (m?.[1]?.startsWith("http")) return m[1];
    }
  } catch { /* fall through */ }
  return link;
}

export async function extractVideo(link: string, serverName?: string): Promise<ExtractedVideo> {
  let finalLink = await resolveBridge(link);
  const compareUrl = normalizeCompareUrl(finalLink);
  let found: ExtractorDef | null = null;

  for (const ext of EXTRACTORS) {
    if (compareUrl.startsWith(normalizeCompareUrl(ext.mainUrl))) { found = ext; break; }
    for (const alias of ext.aliasUrls ?? []) {
      if (compareUrl.startsWith(normalizeCompareUrl(alias))) { found = ext; break; }
    }
    if (found) break;
  }

  if (!found) {
    for (const ext of EXTRACTORS) {
      if (compareUrl.startsWith(stripDomain(ext.mainUrl).toLowerCase())) { found = ext; break; }
      for (const alias of ext.aliasUrls ?? []) {
        if (compareUrl.startsWith(stripDomain(alias).toLowerCase())) { found = ext; break; }
      }
      if (found) break;
    }
  }

  if (!found && serverName) {
    found = EXTRACTORS.find((e) => serverName.toLowerCase().includes(e.name.toLowerCase())) ?? null;
  }

  if (!found) throw new Error(`No extractor found for URL: ${finalLink}`);
  return found.extract(finalLink, serverName);
}

export function listExtractors(): string[] {
  return EXTRACTORS.map((e) => e.name);
}

export function getExtractorRegistry(): ExtractorDef[] {
  return EXTRACTORS;
}
